### ISSUE TITLE
Etykiety

### ISSUE THREAD

**Issue by Zyrafau** [Grabowskiinpg/Projekt_Kalkulator#29]
Niech każdy przydzieli każdemu zadaniu **tego sprintu** jedną etykietkę (label) od 1 do 5. Nie przeciągajcie go do kolumny "Done" tak długo, jak każde zadanie nie będzie mieć po trzy etykietki.

**Comment by Grabowskiinpg** [comment]
Dodane

**Comment by ghost** [comment]
-1

**Comment by Zyrafau** [comment]
Wróćcie jeszcze do poprzedniego projektu (sprintu) i zróbcie to samo, bo nasz Product Owner chce wiedzieć ile komu zapłacić za poprzedni tydzień.
